# Generated by Django 3.2.4 on 2021-07-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodtype',
            fields=[
                ('type', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Seating_Capacity', models.IntegerField()),
                ('Available', models.BooleanField(default=True)),
                ('presentbill', models.FloatField(default=0)),
                ('totalbill', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('phonenumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Remaining', models.IntegerField()),
                ('price', models.FloatField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.foodtype')),
            ],
        ),
    ]
